### ISSUE TITLE
Eprom Diagram

### ISSUE THREAD

**Issue by networkingyuppy** [robsoncouto/eprom#1]
Hi there! 
I was was wondering if you have any detailed pictures of the arduino build of the eprom writer. I'm interested in doing this little project, but the link to teh pictures are broken.
`https://dragaosemchama.com/en/2016/10/arduino-mega-eprom-programmer/`

**Comment by robsoncouto** [comment]
Hello Ben.
I believe I have fixed the links now.
Please have a visit at my website :)

**Comment by networkingyuppy** [comment]
Thank you so much!
